### ISSUE TITLE
About [MASK] augmentation in ColBERT usage example

### ISSUE THREAD

**Issue by thibault-formal** [sebastian-hofstaetter/neural-ranking-kd#1]
Hi @sebastian-hofstaetter ,
Thanks for sharing your trained checkpoints, it's super useful ! 
For ColBERT, if I understood correctly, you used the query augmentation by repeating [MASK] a certain amount of times in the input (8 for your released [checkpoint](https://huggingface.co/sebastian-hofstaetter/colbert-distilbert-margin_mse-T2-msmarco))
I think there is a small mistake in your usage example ([here](https://github.com/sebastian-hofstaetter/neural-ranking-kd/blob/main/minimal_colbert_usage_example.ipynb)), but I wanted to check with you if I understood well: you augment your query with 101, which actually corresponds to [CLS]; I think it should be 103 for [MASK] right ? 

Thanks !

**Comment by sebastian-hofstaetter** [comment]
Hi,
You are right, sorry that is a typo. I used the huggingface tokenizer.mask_token, so [103] to train the model, but simplified it for the usage example. Fixed it, Thanks!
Best,
Sebastian
