### ISSUE TITLE
PreTTr model

### ISSUE THREAD

**Issue by nachshonc** [sebastian-hofstaetter/neural-ranking-kd#2]
Hi, 
Thanks for the really nice package and model files!
Would it be possible to include also the PreTTr model checkpoint?
Thanks.

**Comment by sebastian-hofstaetter** [comment]
Hi,

Sorry for the delay - i uploaded the PreTTR model now on huggingface here: https://huggingface.co/sebastian-hofstaetter/prettr-distilbert-split_at_3-margin_mse-T2-msmarco and added an example in this repo. 

Best,
Sebastian
