### ISSUE TITLE
Candidate passage number in MSMARCO passage re-ranking evaluation?

### ISSUE THREAD

**Issue by ReyonRen** [sebastian-hofstaetter/neural-ranking-kd#3]
Thanks for your contribution!

I'd like to ask how many candidate passages used for MSMARCO passage re-ranking?

Thank you!

**Comment by sebastian-hofstaetter** [comment]
Hi,
Thanks! We used 1000 BM25-candidate passages for re-ranking.
Best,
Sebastian
